name: RNNExplore
channels:
  - defaults
dependencies:
  - python=3.7.2
  - spyder
  - console_shortcut
  - tensorflow=1.15
  - numpy==1.19.2
  - pandas==1.1.3
  - notebook
  - matplotlib
  - seaborn
  - pyarrow
  - scikit-learn
  - opencv
  - tqdm
  - tensorflow-estimator=1.15

